name: fake_process_manager
description: Process Manager for faking processes in tests. Taken from Flutter Tools.
version: 0.1.0+1
homepage: https://github.com/mmcc007/fake_process_manager
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

# TODO(tek08): I don't have control of pub.dev for these packages, so for now,
#   folks can depend on them path-wise, as I have done here.  Each of mmcc007's
#   projects should be cloned into the same parent directory as this project.

dependencies:
  process: ^4.2.4
#  tool_base: ^1.9.5+3
  tool_base:
    path: ../tool_base
  mockito: ^5.3.2
  test: ^1.22.2
dev_dependencies:
  pedantic: ^1.7.0
  tool_base_test:
#    git: https://github.com/mmcc007/tool_base_test.git
    path: ../tool_base_test